# Generated by Django 2.1.15 on 2025-01-06 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table='myapp_task',
        ),
    ]
